#ifndef COMSHAREMEMORY_GLOBAL_H
#define COMSHAREMEMORY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMSHAREMEMORY_LIBRARY)
#  define COMSHAREMEMORY_EXPORT Q_DECL_EXPORT
#else
#  define COMSHAREMEMORY_EXPORT Q_DECL_IMPORT
#endif

#endif // COMSHAREMEMORY_GLOBAL_H
